version: '3.1'
services:
  app:
    container_name: springboot-postgresql
    image: springboot-demo
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=employeedb
#    volumes:
#      - my-db:/
#volumes:
#  my-db: